const courses: string[][] = [
  [
    "Machine Learning",
    "Python",
    "R Programming",
    "Artificial Intelligence",
    "Natural Language Processing(NLP)",
  ],
  [
    "HTML",
    "CSS",
    "Javascript",
    "MERN",
    "MEAN",
    "FullStack",
    "React Native",
    "Express JS",
    "Angular JS",
    "Node JS",
    "C",
    "C++",
    "Advanced JAVA",
    ".NET",
    "MVC",
    "Oracle",
    "Database",
    "SQL",
  ],
  [
    "Photoshop",
    "Corel Draw",
    "Graphic Designing",
    "UI/UX Design",
    "CCNA",
    "Linux",
    "Ethical Hacking",
    "Cloud Computing",
    "AWS",
    "Digital Marketing",
    "Git/GitHub",
    "Operating System",
    "Tally",
    "GST",
    "Excel",
    "MS Word",
    "MS PowerPoint",
    "AutoCAD",
    "Pro-E",
    "SolidWorks",
    "Google SketchUp",
    "Spoken English",
    "Personality Development",
    "Interview Skills",
  ],
];

export default courses;
